server:
  port: 8088

spring:
  # spring security配置
  security:
    user:
      name: admin
      password: admin
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-demo?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 编码格式
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

logging:
  level:
    demo.springboot: debug

