spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        # 自动确认模式
        acknowledge-mode: auto
        retry:
          # 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          enabled: true
          # 重试次数
          max-attempts: 3
          # 单位毫秒
          initial-interval: 5000
        concurrency: 1
        max-concurrency: 10
    virtual-host: /
    # 秒
    requested-heartbeat: 30
    # 毫秒
    connection-timeout: 50000

logging:
  level:
    demo:
      springboot: debug