spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
    publisher-confirm-type: simple
    publisher-returns: true

logging:
  level:
    demo:
      rabbitmq:
        core: debug