# zookeeper client配置
zk:
  lock:
    enable: false

# 限流设置
rate-limiter:
  enable: true
  type: memory

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-demo?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true