## 数据源配置
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.66.134:1521:xe
    username: wms
    password: wms
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      validation-query: select 1 from dual

server:
  port: 8081