## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssmshiro?characterEncoding=utf8&useSSL=true
    username: root
    password: liluo
    driver-class-name: com.mysql.jdbc.Driver
## 日志等级
logging:
  level:
    demo: debug
    org:
      springframework:
        web: debug
## mybatis配置
mybatis:
  type-aliases-package: demo.domain
  mapper-locations: classpath:/demo/mapper/*Mapper.xml